// Complete list of all world countries with phone codes and ISO codes for flag images
export interface Country {
  code: string;  // Phone dial code (without +)
  iso: string;   // ISO 3166-1 alpha-2 (lowercase) for flag CDN
  name: string;  // Country name in French
}

export const ALL_COUNTRIES: Country[] = [
  // Africa - Priority (shown first)
  { code: '243', iso: 'cd', name: 'RD Congo' },
  { code: '237', iso: 'cm', name: 'Cameroun' },
  { code: '225', iso: 'ci', name: "Côte d'Ivoire" },
  { code: '221', iso: 'sn', name: 'Sénégal' },
  { code: '254', iso: 'ke', name: 'Kenya' },
  { code: '255', iso: 'tz', name: 'Tanzanie' },
  { code: '256', iso: 'ug', name: 'Ouganda' },
  { code: '250', iso: 'rw', name: 'Rwanda' },
  { code: '257', iso: 'bi', name: 'Burundi' },
  { code: '234', iso: 'ng', name: 'Nigéria' },
  { code: '233', iso: 'gh', name: 'Ghana' },
  { code: '228', iso: 'tg', name: 'Togo' },
  { code: '229', iso: 'bj', name: 'Bénin' },
  { code: '226', iso: 'bf', name: 'Burkina Faso' },
  { code: '223', iso: 'ml', name: 'Mali' },
  { code: '242', iso: 'cg', name: 'Congo-Brazzaville' },
  { code: '241', iso: 'ga', name: 'Gabon' },
  { code: '235', iso: 'td', name: 'Tchad' },
  { code: '236', iso: 'cf', name: 'Centrafrique' },
  { code: '244', iso: 'ao', name: 'Angola' },
  { code: '258', iso: 'mz', name: 'Mozambique' },
  { code: '260', iso: 'zm', name: 'Zambie' },
  { code: '263', iso: 'zw', name: 'Zimbabwe' },
  { code: '251', iso: 'et', name: 'Éthiopie' },
  { code: '252', iso: 'so', name: 'Somalie' },
  { code: '253', iso: 'dj', name: 'Djibouti' },
  { code: '261', iso: 'mg', name: 'Madagascar' },
  { code: '262', iso: 're', name: 'La Réunion' },
  { code: '264', iso: 'na', name: 'Namibie' },
  { code: '265', iso: 'mw', name: 'Malawi' },
  { code: '266', iso: 'ls', name: 'Lesotho' },
  { code: '267', iso: 'bw', name: 'Botswana' },
  { code: '268', iso: 'sz', name: 'Eswatini' },
  { code: '269', iso: 'km', name: 'Comores' },
  { code: '27', iso: 'za', name: 'Afrique du Sud' },
  { code: '212', iso: 'ma', name: 'Maroc' },
  { code: '213', iso: 'dz', name: 'Algérie' },
  { code: '216', iso: 'tn', name: 'Tunisie' },
  { code: '218', iso: 'ly', name: 'Libye' },
  { code: '220', iso: 'gm', name: 'Gambie' },
  { code: '222', iso: 'mr', name: 'Mauritanie' },
  { code: '224', iso: 'gn', name: 'Guinée' },
  { code: '227', iso: 'ne', name: 'Niger' },
  { code: '230', iso: 'mu', name: 'Maurice' },
  { code: '231', iso: 'lr', name: 'Libéria' },
  { code: '232', iso: 'sl', name: 'Sierra Leone' },
  { code: '238', iso: 'cv', name: 'Cap-Vert' },
  { code: '239', iso: 'st', name: 'São Tomé-et-Príncipe' },
  { code: '240', iso: 'gq', name: 'Guinée équatoriale' },
  { code: '245', iso: 'gw', name: 'Guinée-Bissau' },
  { code: '246', iso: 'io', name: 'Diego Garcia' },
  { code: '248', iso: 'sc', name: 'Seychelles' },
  { code: '249', iso: 'sd', name: 'Soudan' },
  { code: '211', iso: 'ss', name: 'Soudan du Sud' },
  { code: '291', iso: 'er', name: 'Érythrée' },
  { code: '20', iso: 'eg', name: 'Égypte' },
  // Europe
  { code: '32', iso: 'be', name: 'Belgique' },
  { code: '33', iso: 'fr', name: 'France' },
  { code: '49', iso: 'de', name: 'Allemagne' },
  { code: '44', iso: 'gb', name: 'Royaume-Uni' },
  { code: '39', iso: 'it', name: 'Italie' },
  { code: '34', iso: 'es', name: 'Espagne' },
  { code: '351', iso: 'pt', name: 'Portugal' },
  { code: '31', iso: 'nl', name: 'Pays-Bas' },
  { code: '41', iso: 'ch', name: 'Suisse' },
  { code: '43', iso: 'at', name: 'Autriche' },
  { code: '46', iso: 'se', name: 'Suède' },
  { code: '47', iso: 'no', name: 'Norvège' },
  { code: '45', iso: 'dk', name: 'Danemark' },
  { code: '358', iso: 'fi', name: 'Finlande' },
  { code: '353', iso: 'ie', name: 'Irlande' },
  { code: '48', iso: 'pl', name: 'Pologne' },
  { code: '420', iso: 'cz', name: 'Tchéquie' },
  { code: '421', iso: 'sk', name: 'Slovaquie' },
  { code: '36', iso: 'hu', name: 'Hongrie' },
  { code: '40', iso: 'ro', name: 'Roumanie' },
  { code: '359', iso: 'bg', name: 'Bulgarie' },
  { code: '30', iso: 'gr', name: 'Grèce' },
  { code: '385', iso: 'hr', name: 'Croatie' },
  { code: '386', iso: 'si', name: 'Slovénie' },
  { code: '381', iso: 'rs', name: 'Serbie' },
  { code: '387', iso: 'ba', name: 'Bosnie-Herzégovine' },
  { code: '382', iso: 'me', name: 'Monténégro' },
  { code: '389', iso: 'mk', name: 'Macédoine du Nord' },
  { code: '355', iso: 'al', name: 'Albanie' },
  { code: '370', iso: 'lt', name: 'Lituanie' },
  { code: '371', iso: 'lv', name: 'Lettonie' },
  { code: '372', iso: 'ee', name: 'Estonie' },
  { code: '352', iso: 'lu', name: 'Luxembourg' },
  { code: '356', iso: 'mt', name: 'Malte' },
  { code: '357', iso: 'cy', name: 'Chypre' },
  { code: '354', iso: 'is', name: 'Islande' },
  { code: '373', iso: 'md', name: 'Moldavie' },
  { code: '380', iso: 'ua', name: 'Ukraine' },
  { code: '375', iso: 'by', name: 'Biélorussie' },
  { code: '7', iso: 'ru', name: 'Russie' },
  { code: '90', iso: 'tr', name: 'Turquie' },
  // Americas
  { code: '1', iso: 'us', name: 'États-Unis' },
  { code: '1', iso: 'ca', name: 'Canada' },
  { code: '52', iso: 'mx', name: 'Mexique' },
  { code: '55', iso: 'br', name: 'Brésil' },
  { code: '54', iso: 'ar', name: 'Argentine' },
  { code: '57', iso: 'co', name: 'Colombie' },
  { code: '56', iso: 'cl', name: 'Chili' },
  { code: '51', iso: 'pe', name: 'Pérou' },
  { code: '58', iso: 've', name: 'Venezuela' },
  { code: '593', iso: 'ec', name: 'Équateur' },
  { code: '591', iso: 'bo', name: 'Bolivie' },
  { code: '595', iso: 'py', name: 'Paraguay' },
  { code: '598', iso: 'uy', name: 'Uruguay' },
  { code: '53', iso: 'cu', name: 'Cuba' },
  { code: '509', iso: 'ht', name: 'Haïti' },
  { code: '506', iso: 'cr', name: 'Costa Rica' },
  { code: '507', iso: 'pa', name: 'Panama' },
  { code: '502', iso: 'gt', name: 'Guatemala' },
  { code: '504', iso: 'hn', name: 'Honduras' },
  { code: '503', iso: 'sv', name: 'Salvador' },
  { code: '505', iso: 'ni', name: 'Nicaragua' },
  { code: '501', iso: 'bz', name: 'Belize' },
  { code: '592', iso: 'gy', name: 'Guyana' },
  { code: '597', iso: 'sr', name: 'Suriname' },
  // Asia
  { code: '86', iso: 'cn', name: 'Chine' },
  { code: '91', iso: 'in', name: 'Inde' },
  { code: '81', iso: 'jp', name: 'Japon' },
  { code: '82', iso: 'kr', name: 'Corée du Sud' },
  { code: '62', iso: 'id', name: 'Indonésie' },
  { code: '63', iso: 'ph', name: 'Philippines' },
  { code: '66', iso: 'th', name: 'Thaïlande' },
  { code: '84', iso: 'vn', name: 'Vietnam' },
  { code: '60', iso: 'my', name: 'Malaisie' },
  { code: '65', iso: 'sg', name: 'Singapour' },
  { code: '852', iso: 'hk', name: 'Hong Kong' },
  { code: '886', iso: 'tw', name: 'Taïwan' },
  { code: '92', iso: 'pk', name: 'Pakistan' },
  { code: '880', iso: 'bd', name: 'Bangladesh' },
  { code: '94', iso: 'lk', name: 'Sri Lanka' },
  { code: '95', iso: 'mm', name: 'Myanmar' },
  { code: '855', iso: 'kh', name: 'Cambodge' },
  { code: '856', iso: 'la', name: 'Laos' },
  { code: '977', iso: 'np', name: 'Népal' },
  { code: '93', iso: 'af', name: 'Afghanistan' },
  { code: '98', iso: 'ir', name: 'Iran' },
  { code: '964', iso: 'iq', name: 'Irak' },
  // Middle East
  { code: '966', iso: 'sa', name: 'Arabie saoudite' },
  { code: '971', iso: 'ae', name: 'Émirats arabes unis' },
  { code: '974', iso: 'qa', name: 'Qatar' },
  { code: '968', iso: 'om', name: 'Oman' },
  { code: '973', iso: 'bh', name: 'Bahreïn' },
  { code: '965', iso: 'kw', name: 'Koweït' },
  { code: '962', iso: 'jo', name: 'Jordanie' },
  { code: '961', iso: 'lb', name: 'Liban' },
  { code: '963', iso: 'sy', name: 'Syrie' },
  { code: '972', iso: 'il', name: 'Israël' },
  { code: '970', iso: 'ps', name: 'Palestine' },
  { code: '967', iso: 'ye', name: 'Yémen' },
  // Oceania
  { code: '61', iso: 'au', name: 'Australie' },
  { code: '64', iso: 'nz', name: 'Nouvelle-Zélande' },
  { code: '675', iso: 'pg', name: 'Papouasie-Nouvelle-Guinée' },
  { code: '679', iso: 'fj', name: 'Fidji' },
  // Caribbean
  { code: '1876', iso: 'jm', name: 'Jamaïque' },
  { code: '1868', iso: 'tt', name: 'Trinité-et-Tobago' },
  { code: '1809', iso: 'do', name: 'République dominicaine' },
  { code: '590', iso: 'gp', name: 'Guadeloupe' },
  { code: '596', iso: 'mq', name: 'Martinique' },
  { code: '594', iso: 'gf', name: 'Guyane française' },
];

// Flag CDN URL
export const getFlagUrl = (iso: string) =>
  `https://flagcdn.com/w80/${iso.toLowerCase()}.png`;

// Search/filter countries
export const searchCountries = (query: string): Country[] => {
  if (!query || query.trim() === '') return ALL_COUNTRIES;
  const q = query.toLowerCase().trim();
  return ALL_COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.code.includes(q) ||
      c.iso.includes(q) ||
      `+${c.code}`.includes(q)
  );
};
