import { Product, Sale, Expense } from '../types';

export const generateSampleProducts = (userId: string): Product[] => {
  const now = new Date().toISOString();
  return [
    {
      id: 'prod-1',
      name: 'Coca Cola 50cl',
      price: 1,
      stock: 48,
      category: 'drinks',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-2',
      name: 'Pain (Baguette)',
      price: 0.5,
      stock: 25,
      category: 'food',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-3',
      name: 'Savon Lux',
      price: 1.5,
      stock: 15,
      category: 'cosmetics',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-4',
      name: 'Riz 1kg',
      price: 2.5,
      stock: 30,
      category: 'food',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-5',
      name: 'Primus Bière',
      price: 2,
      stock: 60,
      category: 'drinks',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-6',
      name: 'Chemise Homme',
      price: 10,
      stock: 8,
      category: 'clothes',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-7',
      name: 'Huile de cuisine 1L',
      price: 5,
      stock: 12,
      category: 'food',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-8',
      name: 'Fanta Orange',
      price: 1,
      stock: 4,
      category: 'drinks',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-9',
      name: 'Pagne Wax',
      price: 15,
      stock: 6,
      category: 'clothes',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
    {
      id: 'prod-10',
      name: 'Lait Nido',
      price: 7,
      stock: 20,
      category: 'food',
      userId,
      createdAt: now,
      updatedAt: now,
      synced: false,
    },
  ];
};

export const generateSampleSales = (userId: string): Sale[] => {
  const now = Date.now();
  const oneDay = 24 * 60 * 60 * 1000;
  
  return [
    // Today's sales
    {
      id: 'sale-1',
      productId: 'prod-1',
      productName: 'Coca Cola 50cl',
      quantity: 5,
      price: 1,
      totalAmount: 5,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'sale-2',
      productId: 'prod-2',
      productName: 'Pain (Baguette)',
      quantity: 10,
      price: 0.5,
      totalAmount: 5,
      paymentMethod: 'mobileMoney' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'sale-3',
      productId: 'prod-5',
      productName: 'Primus Bière',
      quantity: 12,
      price: 2,
      totalAmount: 24,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    // Yesterday's sales
    {
      id: 'sale-4',
      productId: 'prod-4',
      productName: 'Riz 1kg',
      quantity: 8,
      price: 2.5,
      totalAmount: 20,
      paymentMethod: 'mobileMoney' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - oneDay - 6 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'sale-5',
      productId: 'prod-3',
      productName: 'Savon Lux',
      quantity: 6,
      price: 1.5,
      totalAmount: 9,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - oneDay - 8 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'sale-6',
      productId: 'prod-1',
      productName: 'Coca Cola 50cl',
      quantity: 8,
      price: 1,
      totalAmount: 8,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - oneDay - 10 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    // Two days ago
    {
      id: 'sale-7',
      productId: 'prod-6',
      productName: 'Chemise Homme',
      quantity: 2,
      price: 10,
      totalAmount: 20,
      paymentMethod: 'mobileMoney' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 2 * oneDay).toISOString(),
      synced: false,
    },
    {
      id: 'sale-8',
      productId: 'prod-7',
      productName: 'Huile de cuisine 1L',
      quantity: 4,
      price: 5,
      totalAmount: 20,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 2 * oneDay).toISOString(),
      synced: false,
    },
    {
      id: 'sale-9',
      productId: 'prod-10',
      productName: 'Lait Nido',
      quantity: 3,
      price: 7,
      totalAmount: 21,
      paymentMethod: 'cash' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 3 * oneDay).toISOString(),
      synced: false,
    },
    {
      id: 'sale-10',
      productId: 'prod-5',
      productName: 'Primus Bière',
      quantity: 6,
      price: 2,
      totalAmount: 12,
      paymentMethod: 'mobileMoney' as const,
      currency: 'USD',
      userId,
      createdAt: new Date(now - 3 * oneDay).toISOString(),
      synced: false,
    },
  ];
};

export const generateSampleExpenses = (userId: string): Expense[] => {
  const now = Date.now();
  const oneDay = 24 * 60 * 60 * 1000;
  
  return [
    {
      id: 'expense-1',
      category: 'inventory',
      amount: 50,
      currency: 'USD',
      notes: 'Achat de marchandises au marché',
      userId,
      createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'expense-2',
      category: 'transport',
      amount: 10,
      currency: 'USD',
      notes: 'Transport des marchandises',
      userId,
      createdAt: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'expense-3',
      category: 'rent',
      amount: 30,
      currency: 'USD',
      notes: 'Loyer du mois',
      userId,
      createdAt: new Date(now - oneDay).toISOString(),
      synced: false,
    },
    {
      id: 'expense-4',
      category: 'electricity',
      amount: 15,
      currency: 'USD',
      notes: 'Facture électricité',
      userId,
      createdAt: new Date(now - oneDay - 5 * 60 * 60 * 1000).toISOString(),
      synced: false,
    },
    {
      id: 'expense-5',
      category: 'mobileMoneyFees',
      amount: 3,
      currency: 'USD',
      notes: 'Frais Mobile Money',
      userId,
      createdAt: new Date(now - 2 * oneDay).toISOString(),
      synced: false,
    },
    {
      id: 'expense-6',
      category: 'water',
      amount: 5,
      currency: 'USD',
      notes: 'Eau du mois',
      userId,
      createdAt: new Date(now - 3 * oneDay).toISOString(),
      synced: false,
    },
  ];
};

export const initializeSampleData = async (userId: string) => {
  const { saveProducts, saveSales, saveExpenses } = await import('./storage');
  
  const products = generateSampleProducts(userId);
  const sales = generateSampleSales(userId);
  const expenses = generateSampleExpenses(userId);
  
  await saveProducts(products);
  await saveSales(sales);
  await saveExpenses(expenses);
  
  return { products, sales, expenses };
};
